FROM ubuntu:14.04
MAINTAINER Jun HU <junhufr@gmail.com>

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    openssh-server \
    emacs24-nox \
    sudo

RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd

RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ADD ssh/my_init.sh /sbin/my_init
RUN chown root:root /sbin/my_init
RUN chmod +x /sbin/my_init

RUN apt-get autoremove && apt-get autoclean

EXPOSE 22 9010
CMD ["/sbin/my_init"]
